/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent

fun main() {
    advent.day1.run()
    advent.day2.run()
    advent.day3.run()
    advent.day4.run()
    advent.day5.run()
    advent.day6.run()
    advent.day7.run()
    advent.day8.run()
    advent.day9.run()
}
