/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent

fun main() {
    advent.day1.run()
    advent.day2.run()
    advent.day3.run()
    advent.day4.run()
    advent.day5.run()
    advent.day6.run()
    advent.day7.run()
    advent.day8.run()
    advent.day9.run()
    advent.day10.run()
    advent.day11.run()
    advent.day12.run()
    advent.day13.run()
    advent.day14.run()
    advent.day15.run()
    advent.day16.run()
    advent.day17.run()
    advent.day18.run()
    advent.day19.run()
    advent.day20.run()
    advent.day21.run()
}
